#!/bin/env ruby
# encoding: utf-8

require 'prawn'
require 'prawn/table'

############################################
# NOTE: THIS CLASS EXTENDS PRAWN::DOCUMENT #
############################################

class ErrorDoc < ::Prawn::Document

  def initialize
    # switch to page_layout: :portrait to see without error 
    super(page_size: 'A4', page_layout: :landscape)
    draw
  end


  def rows
    [[{:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]},
      {:content=>"", :borders=>[]}],
     [{:content=>"Chez Vesper, Date: 2014-09-09, Printed: 2014-10-28 (Tue) 03:03, Meals: All Meals, Section: F2 Terrace", :colspan=>25, :height=>20, :borders=>[]}],
     [{:content=>"", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"17:00", :background_color=>"333333", :text_color=>"FFFFFF", :colspan=>4},
      {:content=>"18:00", :background_color=>"333333", :text_color=>"FFFFFF", :colspan=>4},
      {:content=>"19:00", :background_color=>"333333", :text_color=>"FFFFFF", :colspan=>4},
      {:content=>"20:00", :background_color=>"333333", :text_color=>"FFFFFF", :colspan=>4},
      {:content=>"21:00", :background_color=>"333333", :text_color=>"FFFFFF", :colspan=>4},
      {:content=>"22:00", :background_color=>"333333", :text_color=>"FFFFFF", :colspan=>4}],
     [{:content=>"", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"00", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"15", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"30", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"45", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"00", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"15", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"30", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"45", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"00", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"15", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"30", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"45", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"00", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"15", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"30", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"45", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"00", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"15", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"30", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"45", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"00", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"15", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"30", :background_color=>"333333", :text_color=>"FFFFFF"},
      {:content=>"45", :background_color=>"333333", :text_color=>"FFFFFF"}],
     [{:content=>"<font size='11'>0</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"Mayfield, Yolanda, 1 ppl, 2 Ã— b_scotch_grn, 1 Ã— s_applepie, The quick red fox jumps over the lazy brown dog. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", :colspan=>6, :rowspan=>1, :border_right_width=>1.5, :border_bottom_width=>1.5, :background_color=>"EEEEEE"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>3B</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>4B</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"Moore, Barry, 4 ppl, 3 Ã— f_veal, This will be a business dinner. Please prepare the meat well done", :colspan=>2, :rowspan=>1, :border_right_width=>1.5, :border_bottom_width=>1.5, :background_color=>"EEEEEE"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"Jackson, Nicholas, 5 ppl, 2 Ã— f_veal, 3 Ã— c_lunch, 1 Ã— b_yamazaki, 4 Ã— s_chococake, This is a memo", :colspan=>6, :rowspan=>1, :border_right_width=>1.5, :border_bottom_width=>1.5, :background_color=>"EEEEEE"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>5</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>12A</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>13</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>16</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>29A</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"Moore, Barry, 4 ppl, 3 Ã— f_veal, This will be a business dinner. Please prepare the meat well done", :colspan=>2, :rowspan=>1, :border_right_width=>1.5, :border_bottom_width=>1.5, :background_color=>"EEEEEE"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>32</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>35</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>40A</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>41A</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}],
     [{:content=>"<font size='11'>46</font>", :height=>30, :background_color=>"CCCCCC", :align=>:right, :valign=>:center},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :dotted, :dotted, :none], :border_color=>"AAAAAA"},
      {:content=>"", :background_color=>"FFFFFF", :border_lines=>[:none, :solid, :dotted, :none], :border_color=>"AAAAAA"}]]
  end

  def draw
    slots = 96
    self.table(rows,
               split_cells_in_final_row: true,
               width: self.bounds.width,
               column_widths: timetable_col_widths(slots),
               header: 3,
               cell_style: {size: 7, padding: 1, overflow: :truncate, inline_format: true}) do |table|
      table.column(0).padding_right = 3;
      table.columns(1...-1).borders = [:right, :bottom];
      table.columns(1...-1).filter do |cell|
        ['EEEEEE', 'AAAAAA'].include?(cell.background_color)
      end.style(borders: [:top, :bottom, :left, :right])
      table.row(0).columns(0...-1).borders = []
      table.row(1).columns(0...-1).borders = [:bottom]
    end
  end

  def timetable_col_widths(slots)
    table_col_width = 0.05 * self.bounds.width
    slot_width = (self.bounds.width - 1 - table_col_width ) / slots
    # TODO: slots - 1 on next line should be slots
    [table_col_width] + [slot_width] * (slots - 1)
  end
end
@pdf = ErrorDoc.new
@pdf.render_file('test8.pdf')
